### ISSUE TITLE
Consistency in Numbered Sections Between HTML, EPUB, and PDF

### ISSUE THREAD

**Issue by chrisdaaz** [nulib-oer/lantern#34]
Pandoc can [automatically number the section headings](https://pandoc.org/MANUAL.html#option--number-sections) in a document output. Numbering the headings for chapters, sections, subsections, etc. can help instructors and students navigate the textbook document across output formats, since the HTML output does not have page numbers. 

Pandoc settings within Lantern are controlled by [Default files](https://pandoc.org/MANUAL.html#default-files), where [each output format has it's own defaults file](https://github.com/nulib-oer/lantern/tree/main/assets/defaults). 

Currently, the HTML output does not number the sections, but we should figure out if there is a way to configure the default files using Pandoc settings so that the chapters, sections, subsections, etc. are automatically numbered consistently across HTML, PDF, and EPUB outputs. 

## To Do

- Review Pandoc documentation on `--number-sections` option and Default files
- Learn how Lantern configures these settings
- Experiment with a few settings options on a local copy of lantern

**Comment by AngelinaJaglinski** [comment]
From this forum discussion [1](https://groups.google.com/g/pandoc-discuss/c/X15YmSjoPS0/m/u_oK1KtmBAAJ), I followed a link to a GitHub page containing a short filter to number sections [2](https://github.com/jgm/pandoc/issues/6411).  This filter originally appeared in a different forum exchange, mentioned as a solution to another section-numbering issue [3](https://groups.google.com/g/pandoc-discuss/c/_WU9R4i2Y2M/m/fx8OOylkAAAJ).

I have also attached the filter itself to this comment.  (GitHub won't let me attach a .lua file, so this is a .txt version of the filter.)
[number-sections-filter.txt](https://github.com/nulib-oer/lantern/files/6824367/number-sections-filter.txt)
